export default {
  LOGIN_DATA: 'LOGIN_DATA',
  SIGNUP_DATA: 'SIGNUP_DATA',
  FAVORITE_ITEM: 'FAVORITE_ITEM',
  UNFAVORITE_ITEM: 'UNFAVORITE_ITEM',
  CARD_ITEM: 'CARD_ITEM',
  CARD_REMOVE: 'CARD_REMOVE',
  LIKE_UPDATE: 'LIKE_UPDATE',
  CARD_LIST: 'CARD_LIST',
};
